version: '2'

services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9300
    environment:
      - discovery.type=single-node
  kibana:
    build: kibana
    ports:
      - 5601:5601

volumes:
  elasticsearch-data:
    driver: local
